language: objective-c

env:
  global:
    - VLC_VER=2.2.1

  matrix:
    - npm_config_wcjs_runtime="electron" npm_config_wcjs_runtime_version="0.31.1"
    - npm_config_wcjs_runtime="electron" npm_config_wcjs_runtime_version="0.30.6"
    - npm_config_wcjs_runtime="nw" npm_config_wcjs_runtime_version="0.12.3"

before_install:
  - git submodule update --init --recursive
  - wget http://get.videolan.org/vlc/$VLC_VER/macosx/vlc-$VLC_VER.dmg
  - hdiutil mount vlc-$VLC_VER.dmg
  - sudo cp -R "/Volumes/vlc-$VLC_VER/VLC.app" /Applications

script: npm install
